config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines
  get 'search/index'

  devise_for :users
  root 'home#index'

  get 'links/index'

  resources :bus_routes do
    resources :timetables
  end
  resources :distances
  resources :bus_stations do
    collection {post :import}
  end

  post "bus_routes/:id/add_bus_stations", to: "bus_routes#add_bus_stations", as: "add_bus_stations"
  post "bus_routes/:id/destroy_bus_stations", to: "bus_routes#destroy_bus_stations", as: "delete_bus_stations"
  post "bus_routes/:id/update_bus_stations", to: "bus_routes#update_bus_stations", as: "update_bus_stations"
  post "bus_routes/:bus_route_id/timetables/update_nodes",
    to: "timetables#update_nodes", as: "update_nodes"
  post "bus_routes/:bus_route_id/timetables/delete_list_node",
    to: "timetables#delete_list_node", as: "delete_list_node"
  get "bus_routes/:id/search_bus_stop", to: "bus_routes#search_bus_stop", as: "search_bus_stations"

  get "home/show_bus_line/:bus_line_id", to: "home#show_bus_line", as: "show_bus_line"
end

app/models/bus_line.rb
class BusLine < ApplicationRecord
  after_create :create_bus_routes

  has_many :bus_routes

  private

  def create_bus_routes
    BusRoute.transaction do
      BusRoute.create bus_type: 0, bus_line: self
      BusRoute.create bus_type: 1, bus_line: self
    end
  end
end

app/controllers/bus_lines_controller.rb
class BusLinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bus_line, only: [:show, :edit, :update, :destroy]

  # GET /bus_lines
  # GET /bus_lines.json
  def index
    @bus_lines = BusLine.all
  end

  # GET /bus_lines/1
  # GET /bus_lines/1.json
  def show
    @bus_route_di = @bus_line.bus_routes.di.first
    @bus_route_ve = @bus_line.bus_routes.ve.first
    @bus_stations = BusStation.of_ids(@bus_route_di.list_bus_stations) + 
      BusStation.of_ids(@bus_route_ve.list_bus_stations)
    @distances = @bus_route_di.distances + @bus_route_ve.distances
    @hash = Gmaps4rails.build_markers(@bus_stations) do |bus_station, marker|
      marker.lat bus_station.latitude
      marker.lng bus_station.longitude
      marker.infowindow bus_station.title
    end
  end

  # GET /bus_lines/new
  def new
    @bus_line = BusLine.new
  end

  # GET /bus_lines/1/edit
  def edit
  end

  # POST /bus_lines
  # POST /bus_lines.json
  def create
    @bus_line = BusLine.new(bus_line_params)

    respond_to do |format|
      if @bus_line.save
        format.html { redirect_to @bus_line, notice: 'Bus line was successfully created.' }
        format.json { render :show, status: :created, location: @bus_line }
      else
        format.html { render :new }
        format.json { render json: @bus_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_lines/1
  # PATCH/PUT /bus_lines/1.json
  def update
    respond_to do |format|
      if @bus_line.update(bus_line_params)
        format.html { redirect_to @bus_line, notice: 'Bus line was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_line }
      else
        format.html { render :edit }
        format.json { render json: @bus_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_lines/1
  # DELETE /bus_lines/1.json
  def destroy
    @bus_line.destroy
    respond_to do |format|
      format.html { redirect_to bus_lines_url, notice: 'Bus line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_line
      @bus_line = BusLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_line_params
      params.require(:bus_line).permit(:name, :operating_from, :operating_to, :in_charge_unit, :ticket_fee, :description)
    end
end

app/helpers/bus_lines_helper.rb
module BusLinesHelper
end

app/views/bus_lines/_form.html.erb
<%= form_for(@bus_line, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @bus_line.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@bus_line.errors.count, "error") %> prohibited this bus_line from being saved:</h4>

      <ul>
      <% @bus_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :operating_from, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.time_select :operating_from, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :operating_to, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.time_select :operating_to, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :in_charge_unit, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :in_charge_unit, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ticket_fee, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :ticket_fee, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bus_lines/edit.html.erb
<div class="page-header">
  <%= link_to bus_lines_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bus_line, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bus_line</h1>
</div>

<%= render 'form' %>

app/views/bus_lines/index.html.erb
<div class="page-header">
  <%= link_to new_bus_line_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    <%= t "new_bus_line" %>
  <% end %>
  <h1><%= t "list_bus_line" %></h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th><%= t "route_name" %></th>
        <th><%= t "time_start_activity" %></th>
        <th><%= t "time_end_activity" %></th>
        <th><%= t "in_charge_unit" %></th>
        <th><%= t "ticket_fee" %></th>
        <th><%= t "description" %></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bus_lines) do |bus_line| %>
        <td><%= bus_line.name %></td>
        <td><%= bus_line.operating_from.strftime("%H:%M") %></td>
        <td><%= bus_line.operating_to.strftime("%H:%M") %></td>
        <td><%= bus_line.in_charge_unit %></td>
        <td><%= bus_line.ticket_fee %></td>
        <td><%= bus_line.description %></td>
        <td>
          <%= link_to bus_line, class: "btn btn-default" do %>
            <i class="fa fa-eye"></i> Show
          <% end %>
          <%= link_to edit_bus_line_path(bus_line), class: "btn btn-success" do %>
            <i class="fa fa-pencil-square"></i> Edit
          <% end %>
          <%= link_to bus_line, method: :delete, class: "btn btn-warning",
            data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i> Delete
          <% end %>
        </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bus_lines/new.html.erb
<div class="page-header">
  <%= link_to bus_lines_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bus_line</h1>
</div>

<%= render 'form' %>

app/views/bus_lines/show.html.erb
<div class="page-header">
  <%= link_to bus_lines_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    <%= t "back" %>
  <% end %>
  <%= link_to edit_bus_line_path(@bus_line), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    <%= t "edit" %>
  <% end %>
  <h1><%= @bus_line.name %></h1>
</div>

<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading"><%= t "detail_busline" %></div>
    <div class="panel-body">
      <dl class="dl-horizontal">
        <dt><%= t "route_name" %>:</dt>
        <dd><%= @bus_line.name %></dd>

        <dt><%= t "time_start_activity" %>:</dt>
        <dd><%= @bus_line.operating_from.strftime("%H:%M") %></dd>

        <dt><%=  t "time_end_activity" %>:</dt>
        <dd><%= @bus_line.operating_to.strftime("%H:%M") %></dd>

        <dt><%= t "in_charge_unit" %>:</dt>
        <dd><%= @bus_line.in_charge_unit %></dd>

        <dt><%= t "ticket_fee" %>:</dt>
        <dd><%= @bus_line.ticket_fee %></dd>

        <dt><%= t "description" %>:</dt>
        <dd><%= @bus_line.description %></dd>
      </dl>    
    </div>
  </div>
</div>
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading"><%= t "management_busline" %></div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th></th>
              <th><%= t "bus_route" %></th>
              <th><%= t "bus_time" %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= t "go" %></td>
              <td align="center">
                <%= link_to t("edit_bus_route"), @bus_route_di,
                  class: "btn btn-primary" %>
              </td>
              <td align="center"><%= link_to t("edit_bus_time"),
                bus_route_timetables_path(@bus_route_di), class: "btn btn-success" %>
              </td>
            </tr>
            <tr>
              <td><%= t "come" %></td>
              <td align="center">
                <%= link_to t("edit_bus_route"), @bus_route_ve,
                  class: "btn btn-primary" %>
              </td>
              <td align="center"><%= link_to t("edit_bus_time"),
                bus_route_timetables_path(@bus_route_ve), class: "btn btn-success" %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    <% if @hash.any? %>
      var markers = <%= raw @hash.to_json %>
      window.onload = function () {
        var mapOptions = {
            center: new google.maps.LatLng(markers[0].lat, markers[0].lng),
            zoom: 10,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map"), mapOptions);
        var infoWindow = new google.maps.InfoWindow();
        var lat_lng = new Array();
        var latlngbounds = new google.maps.LatLngBounds();
        for (i = 0; i < markers.length; i++) {
            var data = markers[i]
            var myLatlng = new google.maps.LatLng(data.lat, data.lng);
            lat_lng.push(myLatlng);
            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: data.title
            });
            latlngbounds.extend(marker.position);
            (function (marker, data) {
                google.maps.event.addListener(marker, "click", function (e) {
                    infoWindow.setContent(data.infowindow);
                    infoWindow.open(map, marker);
                });
            })(marker, data);
        }
        map.setCenter(latlngbounds.getCenter());
        map.fitBounds(latlngbounds);

        //***********ROUTING****************//

        //Intialize the Path Array
        var path = new google.maps.MVCArray();

        // Intialize the Direction Service
        var service = new google.maps.DirectionsService();

        var bounds = new google.maps.LatLngBounds();

        <% @distances.each do |distance| %>
          var jsonData = <%= raw distance.route.to_json %>
          var path_encode = jsonData[0].overview_polyline.points;
          var path = google.maps.geometry.encoding.decodePath(path_encode);
          for (var i = 0; i < path.length; i++) {
              bounds.extend(path[i]);
          }
          
          var polyline = new google.maps.Polyline({
              path: path,
              strokeColor: '#FF0000',
              strokeOpacity: 0.8,
              strokeWeight: 5,
              fillColor: '#FF0000',
              fillOpacity: 0.8,
              map: map
          });
          polyline.setMap(map);
        <% end %>
        map.fitBounds(bounds);
      }
    <% else %>
      defaultMap("map");
    <% end %>
  });
</script>