config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines
  get 'search/index'

  devise_for :users
  root 'home#index'

  get 'links/index'

  resources :bus_routes do
    resources :timetables
  end
  resources :distances
  resources :bus_stations do
    collection {post :import}
  end

  post "bus_routes/:id/add_bus_stations", to: "bus_routes#add_bus_stations", as: "add_bus_stations"
  post "bus_routes/:id/destroy_bus_stations", to: "bus_routes#destroy_bus_stations", as: "delete_bus_stations"
  post "bus_routes/:id/update_bus_stations", to: "bus_routes#update_bus_stations", as: "update_bus_stations"
  post "bus_routes/:bus_route_id/timetables/update_nodes",
    to: "timetables#update_nodes", as: "update_nodes"
  post "bus_routes/:bus_route_id/timetables/delete_list_node",
    to: "timetables#delete_list_node", as: "delete_list_node"
  get "bus_routes/:id/search_bus_stop", to: "bus_routes#search_bus_stop", as: "search_bus_stations"

  get "home/show_bus_line/:bus_line_id", to: "home#show_bus_line", as: "show_bus_line"
end

app/models/bus_station.rb
class BusStation < ApplicationRecord
  geocoded_by :address
  # after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  # after_create :push_node
  # after_update :update_distance
  # after_save :update_distance

  # has_many :from_distances, class_name: Distance.name, foreign_key: "busstop_from",
  #   dependent: :destroy
  # has_many :to_distances, class_name: Distance.name, foreign_key: "busstop_to",
  #   dependent: :destroy
  # has_many :busstops_from, through: :from_distances, source: :bus_station_from
  # has_many :busstops_to, through: :to_distances, source: :bus_station_to

  has_many :bus_station_routes
  has_many :bus_routes, through: :bus_station_routes
  has_many :nodes

  scope :not_in_object, ->object do
    where("id NOT IN (?)", object.pluck(:id)) if object.any?
  end

  scope :of_ids, -> bus_station_ids do
    where(id: bus_station_ids)
  end

  scope :not_in_routes, -> bus_station_ids do
    where.not(id: bus_station_ids)
  end

  scope :search_address, -> term, bus_station_ids do
    where("LOWER(address) LIKE :address", address: "%#{term}%")
      .where.not(id: bus_station_ids)
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(12)
    (13..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      bus_station = find_by_id(row["id"]) || new
      bus_station.attributes = row.to_hash.slice(*row.to_hash.keys)
      bus_station.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
    when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
    when '.xlsx' then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  private

  def push_node
    g = GraphTimeNode.first
    g.graph.push id
    g.save!
  end

  def update_distance
    GoogleMapsService.configure do |config|
      config.key = 'AIzaSyDBEPeNCZHAyqAYysF2-ykAp8jfd47bxIw'
      config.retry_timeout = 20
      config.queries_per_second = 10
    end

    gmaps = GoogleMapsService::Client.new

    distances = Distance.where("origin = ? or destination = ?", id, id)
    distances.each do |distance|
      origin = BusStation.find_by id: distance.origin
      origin_latlng = [origin.latitude, origin.longitude]
      destination = BusStation.find_by id: distance.destination
      destination_latlng = [destination.latitude, destination.longitude]
      route = gmaps.directions(origin_latlng, destination_latlng,
        mode: 'driving', alternatives: true)
      distance_metter = route[0][:legs][0][:distance][:value]
      distance.update distance_metter: distance_metter, route: route
    end
  end
end

app/controllers/bus_stations_controller.rb
class BusStationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bus_station, only: [:show, :edit, :update, :destroy]

  # GET /bus_stations
  # GET /bus_stations.json
  def index
    @bus_stations = BusStation.all
    @hash = Gmaps4rails.build_markers(@bus_stations) do |bus_station, marker|
      marker.lat bus_station.latitude
      marker.lng bus_station.longitude
      marker.infowindow bus_station.title
    end
  end

  # GET /bus_stations/1
  # GET /bus_stations/1.json
  def show
    @hash = Gmaps4rails.build_markers(@bus_station) do |bus_station, marker|
      marker.lat bus_station.latitude
      marker.lng bus_station.longitude
      marker.infowindow bus_station.title
    end
  end

  # GET /bus_stations/new
  def new
    @bus_station = BusStation.new
  end

  # GET /bus_stations/1/edit
  def edit
  end

  # POST /bus_stations
  # POST /bus_stations.json
  def create
    @bus_station = BusStation.new(bus_station_params)

    respond_to do |format|
      if @bus_station.save
        format.html { redirect_to @bus_station, notice: 'BusStation was successfully created.' }
        format.json { render :show, status: :created, location: @bus_station }
      else
        format.html { render :new }
        format.json { render json: @bus_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_stations/1
  # PATCH/PUT /bus_stations/1.json
  def update
    respond_to do |format|
      if @bus_station.update(bus_station_params)
        format.html { redirect_to @bus_station, notice: 'BusStation was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_station }
      else
        format.html { render :edit }
        format.json { render json: @bus_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_stations/1
  # DELETE /bus_stations/1.json
  def destroy
    @bus_station.destroy
    respond_to do |format|
      format.html { redirect_to bus_stations_url, notice: 'BusStation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    BusStation.import(params[:file])
    redirect_to bus_stations_path, notice: "Products imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_station
      @bus_station = BusStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_station_params
      params.require(:bus_station).permit(:latitude, :longitude, :name, :address, :title)
    end
end

app/views/bus_stations/_bus_station.html.erb
<tr class="bus_station" id="bus_station_<%= bus_station.id %>">
  <td><input type="checkbox" value="<%= bus_station.id %>" class="bus-station-checkbox"></td>
  <td><%= bus_station_counter + 1 %></td>
  <td><%= bus_station.code %></td>
  <td><%= bus_station.address %></td>
</tr>

app/views/bus_stations/_form.html.erb
<%= form_for(@bus_station, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @bus_station.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@bus_station.errors.count, "error") %> prohibited this bus_station from being saved:</h4>

      <ul>
      <% @bus_station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :latitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bus_stations/edit.html.erb
<div class="page-header">
  <%= link_to bus_stations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bus_station, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bus_station</h1>
</div>

<%= render 'form' %>

app/views/bus_stations/index.html.erb
<div class="page-header">
  <%= link_to new_bus_station_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Thêm mới trạm dừng
  <% end %>
  <h1>Danh sách các trạm dừng</h1>
  <h2>Nhập trạm dừng</h2>

  <%= form_tag import_bus_stations_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Nhập" %>
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover" id="table-all-bus-station">
    <thead>
      <tr>
            <th>#</th>
            <th>Latitude</th>
            <th>Longtitude</th>
            <th>Name</th>
            <th>Address</th>
            <th>Title</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bus_stations) do |bus_station| %>
            <td><%= bus_station.id %></td>
            <td><%= bus_station.latitude %></td>
            <td><%= bus_station.longitude %></td>
            <td><%= bus_station.name %></td>
            <td><%= bus_station.address %></td>
            <td><%= bus_station.title %></td>
            <td><%= link_to 'Show', bus_station %></td>
        <td><%= link_to 'Edit', edit_bus_station_path(bus_station) %></td>
        <td><%= link_to 'Destroy', bus_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 1200px; height: 800px;'></div>
</div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/bus_stations/new.html.erb
<div class="page-header">
  <%= link_to bus_stations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bus_station</h1>
</div>

<%= render 'form' %>

app/views/bus_stations/show.html.erb
<div class="page-header">
  <%= link_to bus_stations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_bus_station_path(@bus_station), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show bus_station</h1>
</div>

<dl class="dl-horizontal">
  <dt>Latitude:</dt>
  <dd><%= @bus_station.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @bus_station.longitude %></dd>

  <dt>Name:</dt>
  <dd><%= @bus_station.name %></dd>

  <dt>Address:</dt>
  <dd><%= @bus_station.address %></dd>

  <dt>Title:</dt>
  <dd><%= @bus_station.title %></dd>

</dl>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
</script>