config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines
  get 'search/index'

  devise_for :users
  root 'home#index'

  get 'links/index'

  resources :bus_routes do
    resources :timetables
  end
  resources :distances
  resources :bus_stations do
    collection {post :import}
  end

  post "bus_routes/:id/add_bus_stations", to: "bus_routes#add_bus_stations", as: "add_bus_stations"
  post "bus_routes/:id/destroy_bus_stations", to: "bus_routes#destroy_bus_stations", as: "delete_bus_stations"
  post "bus_routes/:id/update_bus_stations", to: "bus_routes#update_bus_stations", as: "update_bus_stations"
  post "bus_routes/:bus_route_id/timetables/update_nodes",
    to: "timetables#update_nodes", as: "update_nodes"
  post "bus_routes/:bus_route_id/timetables/delete_list_node",
    to: "timetables#delete_list_node", as: "delete_list_node"
  get "bus_routes/:id/search_bus_stop", to: "bus_routes#search_bus_stop", as: "search_bus_stations"

  get "home/show_bus_line/:bus_line_id", to: "home#show_bus_line", as: "show_bus_line"
end

app/models/distance.rb
require_dependency 'edge'

class Distance < ApplicationRecord
  belongs_to :bus_route
  serialize :route, Array

  # after_create :build_graph
  # after_destroy :remove_edge
  # after_update :update_edge

  validates :origin, presence: true
  validates :destination, presence: true
  validates_uniqueness_of :origin, scope: [:destination, :bus_route_id]

  def get_distance
    bus_station_from = BusStation.find_by id: origin
    bus_station_to = BusStation.find_by id: destination

    @matrix = GoogleDistanceMatrix::Matrix.new
    @matrix.configure do |config|
      config.mode = 'driving'
      config.avoid = 'tolls'
      config.google_api_key = "AIzaSyCzjkYK_6usldy2pnjk7COj7CM0qf2w388"
    end

    lat_lng = GoogleDistanceMatrix::BusStation.new lng: bus_station_from.longitude, lat: bus_station_from.latitude
    dest_address = GoogleDistanceMatrix::BusStation.new lng: bus_station_to.longitude, lat: bus_station_to.latitude

    @matrix.origins << lat_lng
    @matrix.destinations << dest_address
    @matrix.route_for(origin: lat_lng, destination: dest_address).distance_in_meters
  end

  private

  def build_graph
    g = GraphTimeNode.first
    g.graph.connect_mutually origin, destination, id, distance_metter
    g.save!
  end

  def update_edge
    g = GraphTimeNode.first
    return unless g.graph.edges.find {|edge| edge.id == id }
    g.graph.edges.each { |edge|
      if edge.id == id
        edge.length = distance_metter
      end
    }
    g.save!
  end

  def remove_edge
    g = GraphTimeNode.first
    g.graph.edges.delete_if {|obj| obj.id == id}
    g.save!
  end
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  before_action :set_distance, only: [:show, :edit, :update, :destroy]

  # GET /distances
  # GET /distances.json
  def index
    @distances = Distance.all
  end

  # GET /distances/1
  # GET /distances/1.json
  def show
  end

  # GET /distances/new
  def new
    @distance = Distance.new
  end

  # GET /distances/1/edit
  def edit
  end

  # POST /distances
  # POST /distances.json
  def create
    @distance = Distance.new(distance_params)

    bus_station_from_id = params[:distance][:busstop_from].to_i
    bus_station_to_id = params[:distance][:busstop_to].to_i

    distance_meters = get_distance(bus_station_from_id, bus_station_to_id)

    @distance.distance_metter = distance_meters
    respond_to do |format|
      if @distance.save
        format.html { redirect_to @distance, notice: 'Distance was successfully created.' }
        format.json { render :show, status: :created, location: @distance }
      else
        format.html { render :new }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distances/1
  # PATCH/PUT /distances/1.json
  def update
    bus_station_from_id = params[:distance][:busstop_from].to_i
    bus_station_to_id = params[:distance][:busstop_to].to_i

    distance_meters = get_distance(bus_station_from_id, bus_station_to_id)

    params[:distance][:distance_metter] = distance_meters
    respond_to do |format|
      if @distance.update(distance_params)
        format.html { redirect_to @distance, notice: 'Distance was successfully updated.' }
        format.json { render :show, status: :ok, location: @distance }
      else
        format.html { render :edit }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distances/1
  # DELETE /distances/1.json
  def destroy
    @distance.destroy
    respond_to do |format|
      format.html { redirect_to distances_url, notice: 'Distance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distance
      @distance = Distance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distance_params
      params.require(:distance).permit(:busstop_from, :busstop_to, :distance_metter)
    end

    def get_distance bus_station_from_id, bus_station_to_id
      bus_station_from = BusStation.find_by id: bus_station_from_id
      bus_station_to = BusStation.find_by id: bus_station_to_id

      @matrix = GoogleDistanceMatrix::Matrix.new
      @matrix.configure do |config|
        config.mode = 'driving'
        config.avoid = 'tolls'
        config.google_api_key = "AIzaSyCzjkYK_6usldy2pnjk7COj7CM0qf2w388"
      end

      lat_lng = GoogleDistanceMatrix::BusStation.new lng: bus_station_from.longitude, lat: bus_station_from.latitude
      dest_address = GoogleDistanceMatrix::BusStation.new lng: bus_station_to.longitude, lat: bus_station_to.latitude

      @matrix.origins << lat_lng
      @matrix.destinations << dest_address
      @matrix.route_for(origin: lat_lng, destination: dest_address).distance_in_meters
      binding.pry
    end
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/views/distances/_form.html.erb
<%= form_for(@distance, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @distance.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@distance.errors.count, "error") %> prohibited this distance from being saved:</h4>

      <ul>
      <% @distance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :busstop_from, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :busstop_from, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :busstop_to, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :busstop_to, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :distance_metter, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :distance_metter, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/distances/edit.html.erb
<div class="page-header">
  <%= link_to distances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @distance, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing distance</h1>
</div>

<%= render 'form' %>

app/views/distances/index.html.erb
<div class="page-header">
  <%= link_to new_distance_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Distance
  <% end %>
  <h1>Listing distances</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Busstop from</th>
            <th>Busstop to</th>
            <th>Distance metter</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @distances) do |distance| %>
            <td><%= distance.busstop_from %></td>
            <td><%= distance.busstop_to %></td>
            <td><%= distance.distance_metter %></td>
            <td><%= link_to 'Show', distance %></td>
        <td><%= link_to 'Edit', edit_distance_path(distance) %></td>
        <td><%= link_to 'Destroy', distance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/distances/new.html.erb
<div class="page-header">
  <%= link_to distances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New distance</h1>
</div>

<%= render 'form' %>

app/views/distances/show.html.erb
<div class="page-header">
  <%= link_to distances_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_distance_path(@distance), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show distance</h1>
</div>

<dl class="dl-horizontal">
  <dt>Busstop from:</dt>
  <dd><%= @distance.busstop_from %></dd>

  <dt>Busstop to:</dt>
  <dd><%= @distance.busstop_to %></dd>

  <dt>Distance metter:</dt>
  <dd><%= @distance.distance_metter %></dd>

</dl>