config/routes.rb
Rails.application.routes.draw do
  resources :bus_lines
  get 'search/index'

  devise_for :users
  root 'home#index'

  get 'links/index'

  resources :bus_routes do
    resources :timetables
  end
  resources :distances
  resources :bus_stations do
    collection {post :import}
  end

  post "bus_routes/:id/add_bus_stations", to: "bus_routes#add_bus_stations", as: "add_bus_stations"
  post "bus_routes/:id/destroy_bus_stations", to: "bus_routes#destroy_bus_stations", as: "delete_bus_stations"
  post "bus_routes/:id/update_bus_stations", to: "bus_routes#update_bus_stations", as: "update_bus_stations"
  post "bus_routes/:bus_route_id/timetables/update_nodes",
    to: "timetables#update_nodes", as: "update_nodes"
  post "bus_routes/:bus_route_id/timetables/delete_list_node",
    to: "timetables#delete_list_node", as: "delete_list_node"
  get "bus_routes/:id/search_bus_stop", to: "bus_routes#search_bus_stop", as: "search_bus_stations"

  get "home/show_bus_line/:bus_line_id", to: "home#show_bus_line", as: "show_bus_line"
end

app/models/bus_route.rb
class BusRoute < ApplicationRecord
  has_many :bus_station_routes
  has_many :bus_stations, through: :bus_station_routes
  has_many :distances
  has_many :time_nodes
  has_many :list_time_nodes
  belongs_to :bus_line
  enum bus_type: [:di, :ve]

  serialize :list_bus_stations, Array
end

app/controllers/bus_routes_controller.rb
require 'google_maps_service'

class BusRoutesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bus_route, except: :index
  before_action :list_bus_stations, only: [:add_bus_stations, :destroy_bus_stations]
  before_action :set_global_api
  after_action :set_route, only: [:add_bus_stations, :destroy_bus_stations, :update_bus_stations]
  after_action :delete_nodes, only: :destroy_bus_stations
  after_action :add_nodes, only: :add_bus_stations
  after_action :update_links, only: :update_bus_stations

  def index
    @bus_routes = BusRoute.all
  end

  def show
    @bus_line = @bus_route.bus_line
    @bus_stations = BusStation.of_ids(@bus_route.list_bus_stations)
      .index_by(&:id).values_at(*@bus_route.list_bus_stations)
    @another_bus_stations = BusStation.not_in_routes(@bus_route.list_bus_stations)
    @distances = @bus_route.distances
    @hash = Gmaps4rails.build_markers(@bus_stations) do |bus_station, marker|
      marker.lat bus_station.latitude
      marker.lng bus_station.longitude
      marker.infowindow bus_station.address
    end
  end

  # GET /bus_routes/new
  def new
    @bus_route = BusRoute.new
  end

  def edit
  end

  def create
    @bus_route = BusRoute.new(bus_route_params)

    respond_to do |format|
      if @bus_route.save
        format.html { redirect_to @bus_route, notice: 'Bus route was successfully created.' }
        format.json { render :show, status: :created, location: @bus_route }
      else
        format.html { render :new }
        format.json { render json: @bus_route.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bus_route.update(bus_route_params)
        format.html { redirect_to @bus_route, notice: 'Bus route was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_route }
      else
        format.html { render :edit }
        format.json { render json: @bus_route.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bus_route.destroy
    respond_to do |format|
      format.html { redirect_to bus_routes_url, notice: 'Bus route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_bus_stations
    @bus_route.list_bus_stations += @list_bus_stations
    @bus_route.save
    redirect_to @bus_route
  end

  def destroy_bus_stations
    @bus_route.list_bus_stations -= @list_bus_stations
    @bus_route.save
    redirect_to @bus_route
  end

  def update_bus_stations
    @bus_route.list_bus_stations = params[:list_bus_stations].map(&:to_i)
    @bus_route.save!
    redirect_to @bus_route
  end

  def search_bus_stop
    term = params[:term]
    @bus_stops = BusStation.search_address term, @bus_route.list_bus_stations
    respond_to do |format|
      format.js
    end
  end

  private
    def set_bus_route
      @bus_route = BusRoute.find(params[:id])
    end

    def bus_route_params
      params.require(:bus_route).permit(:name, list_bus_stations: [])
    end

    def list_bus_stations
      @list_bus_stations = params[:list_bus_stations].map(&:to_i)
      return if @list_bus_stations.any?
      flash[:alert] = t "dashboard.whitelist.update.not_choose"
      redirect_to request.referer
    end

    def set_route
      list_bus_stations = @bus_route.list_bus_stations
      Distance.transaction do
        @bus_route.distances.destroy_all
        (list_bus_stations.length - 1).times do |i|
          origin = BusStation.find_by id: list_bus_stations[i]
          origin_latlng = [origin.latitude, origin.longitude]
          destination = BusStation.find_by id: list_bus_stations[i+1]
          destination_latlng = [destination.latitude, destination.longitude]
          route = @gmaps.directions(origin_latlng, destination_latlng,
            mode: 'driving', alternatives: true)
          distance_metter = route[0][:legs][0][:distance][:value]
          Distance.create origin: origin.id, destination: destination.id,
            bus_route: @bus_route, route: route, distance_metter: distance_metter
        end
      end
    end

    def delete_nodes
      @list_bus_stations.each do |bus_station_id|
        nodes = TimeNode.where(bus_route: @bus_route, bus_station_id: bus_station_id)
        nodes.each do |node|
          destination_links = Link.where(destination: node.id)
          origin_links = Link.where(origin: node.id)
          destination_links.each do |des|
            origin_links.each do |ori|
              Link.create origin: des.origin, destination: ori.destination, 
                cost: des.cost + ori.cost
            end
          end
          destination_links.delete_all
          origin_links.delete_all
          @bus_route.list_time_nodes.each do |l|
            l.list.delete_if {|x| x == node.id}
            l.save
          end
        end
        nodes.delete_all
        @bus_route.list_time_nodes.each do |l|
          l.destroy if l.list.empty?
        end
      end
    end

    def add_nodes
      @bus_route.list_time_nodes.each do |ln|
        previous_list_length = ln.list.length
        @list_bus_stations.each do |bus_station_id|
          node = TimeNode.create bus_route: @bus_route, bus_station_id: bus_station_id,
            list_time_node: ln, arrival_time: "00:00"
          ln.list.push node.id
        end
        ln.save
        new_list_nodes = TimeNode.of_ids(ln.list.drop(previous_list_length-1))
          .index_by(&:id).values_at(*ln.list.drop(previous_list_length-1))

        (new_list_nodes.length-1).times do |i|
          Link.create origin: new_list_nodes[i].id, destination: new_list_nodes[i+1].id,
            cost: new_list_nodes[i+1].arrival_time - new_list_nodes[i].arrival_time 
        end
      end
    end

    def update_links
      list_bus_stations = @bus_route.list_bus_stations
      @bus_route.list_time_nodes.each do |ln|
        previous_list = ln.list
        nodes = TimeNode.of_ids(previous_list)
        new_list = []
        list_bus_stations.each do |lp|
          new_list.push(nodes.find{|n| n.bus_station_id == lp}.id)
        end
        (previous_list.length-1).times do |i|
          Link.find_by(origin: previous_list[i], destination: previous_list[i+1]).destroy
        end

        new_list_nodes = TimeNode.of_ids(new_list)
          .index_by(&:id).values_at(*new_list)
        (new_list.length-1).times do |i|
          Link.create origin: new_list_nodes[i].id, destination: new_list_nodes[i+1].id,
            cost: new_list_nodes[i+1].arrival_time - new_list_nodes[i].arrival_time
        end
        ln.list = new_list
        ln.save
      end
    end
end

app/helpers/bus_routes_helper.rb
module BusRoutesHelper
end

app/views/bus_routes/_form.html.erb
<%= form_for(@bus_route, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @bus_route.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@bus_route.errors.count, "error") %> prohibited this bus_route from being saved:</h4>

      <ul>
      <% @bus_route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bus_routes/_list_bus_stop.html.erb
<% bus_stations.each_with_index do |bus_station, index| %>
  <tr class="search-user-image">
    <td>
      <%= check_box_tag "bus_stations[]", bus_station.id, false, 
        id: "user-add-#{bus_station.id}", class: "user-add",
        onclick: "check_user(this)" %>
      <strong><%= bus_station.name %></strong>
    </td>
  </tr>
<% end %>

app/views/bus_routes/edit.html.erb
<div class="page-header">
  <%= link_to bus_routes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bus_route, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bus_route</h1>
</div>

<%= render 'form' %>

app/views/bus_routes/index.html.erb
<div class="page-header">
  <%= link_to new_bus_route_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Bus route
  <% end %>
  <h1>Listing bus_routes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Type</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @bus_routes) do |bus_route| %>
        <td><%= bus_route.bus_type %></td>
        <td><%= link_to 'Show', bus_route %></td>
        <td><%= link_to 'Edit', edit_bus_route_path(bus_route) %></td>
        <td><%= link_to 'Destroy', bus_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bus_routes/new.html.erb
<div class="page-header">
  <%= link_to bus_routes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bus_route</h1>
</div>

<%= render 'form' %>

app/views/bus_routes/search_bus_stop.js.erb
$('#table-bus_station tbody').html("<%= j render @bus_stops %>");

app/views/bus_routes/show.html.erb
<div id="loader" style="display: none;"></div>
<div class="page-header">
  <%= link_to t("edit_bus_time"), bus_route_timetables_path(@bus_route), class: "btn btn-success" %>
  <%= link_to bus_routes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    <%= t "back" %>
  <% end %>
  <h1>
    <%= @bus_line.name %>
    <% if @bus_route.di? %>
      (Lượt đi)
    <% else %>
      (Lượt về)
    <% end %>
  </h1>
</div>

<input type="hidden" id="bus-route-id" data-id="<%= @bus_route.id %>">
<div class="container">
  <div class="row">
    <div class="col-md-6 paddingbottom">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t "bus_route_infomation" %></h3>
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal">
            <dt><%= t "route_name" %>:</dt>
            <dd><%= @bus_line.name %></dd>

            <dt><%= t "luot" %>: </dt>
            <% if @bus_route.di? %>
              <dd>đi</dd>
            <% else %>
              <dd>về</dd>
            <% end %>

            <dt><%= t "time_start_activity" %>:</dt>
            <dd><%= @bus_line.operating_from.strftime("%H:%M") %></dd>

            <dt><%=  t "time_end_activity" %>:</dt>
            <dd><%= @bus_line.operating_to.strftime("%H:%M") %></dd>

            <dt><%= t "in_charge_unit" %>:</dt>
            <dd><%= @bus_line.in_charge_unit %></dd>

            <dt><%= t "ticket_fee" %>:</dt>
            <dd><%= @bus_line.ticket_fee %></dd>

            <dt><%= t "start_bus_station" %>:</dt>
            <% if @bus_station.present? %>
            <dd><%= @bus_stations.first.address %></dd>
            <% end %>


            <dt><%= t "end_bus_station" %>:</dt>
            <% if @bus_station.present? %>
            <dd><%= @bus_stations.last.address %></dd>
            <% end %>
          </dl>    
        </div>
      </div>
    </div>
    <div class="col-md-6 paddingbottom">
      <div style='width: auto;'>
        <div id="map" style='width: auto; height: 400px;'></div>
      </div>
    </div>
    <div class="col-md-6 paddingbottom">
      <div class="row">
        <div class="col-md-4">
          <button class="btn btn-primary" id="btn-add-bus-stations-routes">
            <%= t "add_bus_station" %>
          </button>
        </div>
      </div>
      <div class="table-responsive paddingtop">
        <table id="table-bus-station" class="display select">
          <thead>
            <tr>
              <th></th>
              <th>#</th>
              <th><%= t "code_bus_station" %></th>
              <th><%= t "address" %></th>
            </tr>
          </thead>

          <tbody>
            <%= render @another_bus_stations %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-6 paddingbottom">
      <div class="row">
        <div class="col-md-8">
          <input type="button" id="move-up" class="btn btn-default" value="<%= t "up" %>">
          <input type="button" id="move-down" class="btn btn-default" value="<%= t "down" %>">
          <input type="button" id="save-added-bus-station" class="btn btn-success" value="<%= t "save" %>">
        </div>
        <div class="col-md-4">
          <%= button_tag type: :submit, class: "btn btn-danger pull-right",
            id: "btn-delete-bus-stations-routes" do %>
            <i class="gi gi-remove_2"></i> <%= t "delete_bus_station" %>
          <% end %>
        </div>
      </div>
      <div class="table-responsive paddingtop">
        <table class="display select" id="table-added-bus-station">
          <thead>
            <tr>
              <th></th>
              <th>#</th>
              <th><%= t "code_bus_station" %></th>
              <th><%= t "address" %></th>
            </tr>
          </thead>

          <tbody>
            <% counter = 0 %>
            <% @bus_stations.each do |bus_station| %>
              <%= render bus_station, bus_station_counter: counter %>
              <% counter = counter + 1 %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

$(document).ready(function(){
  <% if @hash.any? %>
    var markers = <%= raw @hash.to_json %>
    window.onload = function () {
      var mapOptions = {
          center: new google.maps.LatLng(markers[0].lat, markers[0].lng),
          zoom: 10,
          mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map"), mapOptions);
      var infoWindow = new google.maps.InfoWindow();
      var lat_lng = new Array();
      var latlngbounds = new google.maps.LatLngBounds();
      for (i = 0; i < markers.length; i++) {
          var data = markers[i]
          var myLatlng = new google.maps.LatLng(data.lat, data.lng);
          lat_lng.push(myLatlng);
          var marker = new google.maps.Marker({
              position: myLatlng,
              map: map,
              title: data.title,
              icon: "https://thumb.ibb.co/dJ6yQk/busstop.png"
          });
          latlngbounds.extend(marker.position);
          (function (marker, data) {
              google.maps.event.addListener(marker, "click", function (e) {
                  infoWindow.setContent(data.infowindow);
                  infoWindow.open(map, marker);
              });
          })(marker, data);
      }
      map.setCenter(latlngbounds.getCenter());
      map.fitBounds(latlngbounds);

      //***********ROUTING****************//

      //Intialize the Path Array
      var path = new google.maps.MVCArray();

      // Intialize the Direction Service
      var service = new google.maps.DirectionsService();

      var bounds = new google.maps.LatLngBounds();

      <% @distances.each do |distance| %>
        var jsonData = <%= raw distance.route.to_json %>
        var path_encode = jsonData[0].overview_polyline.points;
        var path = google.maps.geometry.encoding.decodePath(path_encode);
        for (var i = 0; i < path.length; i++) {
            bounds.extend(path[i]);
        }
        
        var polyline = new google.maps.Polyline({
            path: path,
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 5,
            fillColor: '#FF0000',
            fillOpacity: 0.8,
            map: map
        });
        polyline.setMap(map);
      <% end %>
      map.fitBounds(bounds);
    }
  <% else %>
    defaultMap("map");
  <% end %>
})
</script>